#!/bin/bash

CWD=`pwd`
PACKAGE=pam_mysql
DOCKER_IMAGE=docker-registry.jc21.net.au/rpmbuild:el7
BUILD_SPEC_ARGS="-r /home/rpmbuilder/rpmbuild/DEPS/*/*.rpm"

BUILD_TAG=centos7-$PACKAGE-manual-run

rm -rf RPMS SRPMS DEPS
mkdir -p {RPMS,SRPMS,DEPS} && chmod -R 777 {RPMS,SRPMS,DEPS}

# Copy deps manually
# no deps

CMD="sudo docker run --rm \
  --name rpmbuild-$BUILD_TAG \
  -v $CWD/DEPS:/home/rpmbuilder/rpmbuild/DEPS \
  -v $CWD/RPMS:/home/rpmbuilder/rpmbuild/RPMS \
  -v $CWD/SRPMS:/home/rpmbuilder/rpmbuild/SRPMS \
  -v $CWD/SPECS:/home/rpmbuilder/rpmbuild/SPECS \
  -v $CWD/SOURCES:/home/rpmbuilder/rpmbuild/SOURCES \
  $DOCKER_IMAGE \
  /bin/build-spec $BUILD_SPEC_ARGS -- /home/rpmbuilder/rpmbuild/SPECS/$PACKAGE.spec"

$CMD

exit $?

